# Generated by Django 4.0.4 on 2022-06-16 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_associado'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='blog_associado',
            new_name='Associado',
        ),
    ]
